import {LOADING_INIT_RESTAURANT_DATA, LOADING_TOGGLE_RESTAURANT, LOADING_UPDATE_RESTAURANT_STATUS} from "module/restaurant/type";

export const LOADING_LOGIN = "LOADING_LOGIN";
export const LOADING_LOGOUT = "LOADING_LOGOUT";
export const LOADING_INIT_GLOBAL_DATA = "LOADING_INIT_GLOBAL_DATA";

export const GlobalLoadingKey = [LOADING_INIT_GLOBAL_DATA, LOADING_LOGIN, LOADING_LOGOUT, LOADING_INIT_RESTAURANT_DATA, LOADING_TOGGLE_RESTAURANT, LOADING_UPDATE_RESTAURANT_STATUS];

export interface State {
    supportPhone: null | string;
    navigationBarOpen: boolean;
}
