export const REMEMBER_ME = "RP_REMEMBER_ME";
export const PASSWORD_KEY = "PASSWORD_KEY";
export const EMAIL_KEY = "EMAIL_KEY";
export const PAUSE_ORDER_MODAL_CLOSE_BY_RESTAURANT = "PAUSE_ORDER_MODAL_CLOSE_BY_RESTAURANT";

export interface State {}
