name: Notify Slack on Push

on:
  push:
    branches:
      - master  # 监控 master 分支的推送事件

jobs:
  notify:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行

    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3  # 使用 Slack 通知 Action
        with:
          status: ${{ job.status }}  # 传递作业状态
          payload: |
            {
              "text": "代码已推送到 master 分支！",
              "attachments": [
                {
                  "title": "提交信息",
                  "text": "${{ github.event.head_commit.message }}",
                  "color": "#36a64f"
                },
                {
                  "title": "提交者",
                  "text": "${{ github.event.head_commit.author.name }}",
                  "color": "#f39c12"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # 从 Secrets 中获取 Slack Webhook URL
