# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Post an inline text message
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Leave a kind message after updates
    runs-on: ubuntu-latest
    steps:
      - name: Check Webhook URL
        run: echo ${{ secrets.SLACK_WEBHOOK_URL }}  # 确认 Secrets 是否被正确读取

      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}  # 使用 Secrets 中的 Webhook URL
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Greetings!"
            }
